<a href="https://colab.research.google.com/github/RohithRoshanMurali/daily-python-training/blob/main/20_may_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practise Section : 20 May

##Q1

In [ ]:
# Task:
# 1. Create a 6x6 NumPy array with values from 10 to 360 (step of 10).
# 2. Reshape it into a matrix.
# 3. Replace:
#    - Elements divisible by both 3 and 5 with -1
#    - Even elements with 0 (except the ones already -1)
#    - Remaining with 1

In [ ]:
import pandas as pd
import numpy as np

#Creating array and reshaping it to a matrix
arr = np.arange(10,361,10).reshape(6,6)

#Replace
arr=np.where((arr%3==0)&(arr%5==0),-1,arr)
arr=np.where((arr%2==0)&(arr!=-1),0,arr)
arr=np.where(arr!=0,1,arr)

print(arr)




[[0 0 1 0 0 1]
 [0 0 1 0 0 1]
 [0 0 1 0 0 1]
 [0 0 1 0 0 1]
 [0 0 1 0 0 1]
 [0 0 1 0 0 1]]


##Q2

In [ ]:
import re
text = """
2023-08-15 10:00:01 [INFO] User: alice | Action: login | Status: SUCCESS
2023-08-15 10:01:43 [WARN] User: bob | Action: upload | Status: RETRY
2023-08-15 10:02:09 [ERROR] User: charlie | Action: download | Status: FAILED
"""

# Task:
# Extract a list of dictionaries like:
# [{'user': 'alice', 'action': 'login', 'status': 'SUCCESS'}, ...]

In [ ]:
#User Extraction
user=re.findall(r'User:\s(\w+)',text)

#Action extraction
action=re.findall(r'Action:\s(\w+)',text)

#Status extraction
status=re.findall(r'Status:\s([A-Z]+)',text)

#Dictionary
df=dict()
df['user']=user
df['action']=action
df['status']=status

df=pd.DataFrame(df)
df


user    action   status
0    alice     login  SUCCESS
1      bob    upload    RETRY
2  charlie  download   FAILED

##Q3

In [ ]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'Region': ['East', 'West', 'East', 'West', 'East', 'West', 'North', 'North'],
    'Month': ['Jan', 'Jan', 'Feb', 'Feb', 'Mar', 'Mar', 'Jan', 'Feb'],
    'Sales': [1000, 1200, 1300, 1400, 1100, 1150, 900, 950],
    'Profit': [200, 240, 260, 300, 210, 230, 180, 190]
})

# 🧠 Task:
# 1. Group the data by Region and Month
# 2. Calculate:
#    - Total Sales per group
#    - Average Profit per group
# 3. Filter the result to include only groups with:
#    - Total Sales > 2500
#    - Avg_Profit > 250
# 4. Reset the index and rename columns to 'Total_Sales' and 'Avg_Profit'
# 5. Sort the final result by Avg_Profit in descending order

In [ ]:
#Grouping Data and calculations
df_new=df.groupby(['Region','Month']).agg(
    Total_Sales=('Sales','sum'),
    Average_Profit=('Profit','mean')
)

#Filtering resutls
df_filtered=df_new[((df_new['Total_Sales']>1000)&(df_new['Average_Profit']>150))]

#Renaming Cols
df_filtered=df_filtered.rename(columns={'Total_Sales':'Total_Sales', 'Average_Profit':'Avg_Profit'})

#Sort
df_filtered=df_filtered.sort_values(by='Avg_Profit', ascending=False)

#Display
df_filtered=df_filtered.reset_index()
df_filtered

Region Month  Total_Sales  Avg_Profit
0   West   Feb         1400       300.0
1   East   Feb         1300       260.0
2   West   Jan         1200       240.0
3   West   Mar         1150       230.0
4   East   Mar         1100       210.0

##Q4


In [ ]:
# 1. Convert 'Date' to datetime (if not already), and extract 'Month' and 'Year'
# 2. Remove Feb 29 (if present)
# 3. For each city and month, calculate:
#    - Average PM2.5
#    - Max NO2
#    - Min Temperature
# 4. Filter the results:
#    - Keep only months where Avg PM2.5 > 150 and Max NO2 > 80
# 5. Add a column 'Unhealthy Month' = True if both conditions met
# 6. Sort by city and month
# 7. Return the cleaned and filtered summary DataFrame

In [15]:
# 📦 Data Setup (Use this to run the question)
import pandas as pd
import numpy as np

np.random.seed(42)

df = pd.DataFrame({
    'Date': pd.date_range(start='2022-01-01', periods=730),
    'City': ['Delhi'] * 365 + ['Mumbai'] * 365,
    'PM2.5': np.random.uniform(40, 250, size=730),
    'NO2': np.random.uniform(20, 100, size=730),
    'Temperature': np.random.uniform(15, 45, size=730)
})



In [19]:
#Cleaning Data Frame
df.columns=[col.strip().lower().replace(" ","_") for col in df.columns]

#Date Conversion
df['date']=pd.to_datetime(df['date'])

#Month and year extraction
df['month']=df['date'].dt.month
df['year']=df['date'].dt.year

#Removing Feb 29
df=df[~((df['month']==2)&(df['date'].dt.day==29))]

#Calculation
df_new=df.groupby(['city','month']).agg(
    average_pm25=('pm2.5','mean'),
    max_no2=('no2','max'),
    min_temperature=('temperature','min')
    )

#Filtering
df_filtered=df_new[(df_new['average_pm25']>150)&(df_new['max_no2']>80)]


#Unhealthy Month
df_filtered['unhealthy_month']=True

#Sort
df_filtered=df_filtered.sort_values(by=['city','month'])

#Final
df_filtered=df_filtered.reset_index()
df_filtered





<ipython-input-19-6c5849ad8891>:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['unhealthy_month']=True


city  month  average_pm25    max_no2  min_temperature  unhealthy_month
0   Delhi      8    153.154041  94.946379        15.774357             True
1   Delhi      9    164.736290  96.018988        16.733417             True
2  Mumbai      2    158.723376  90.290399        16.295212             True
3  Mumbai      5    158.985529  98.718212        15.725753             True
4  Mumbai      6    167.540773  93.667828        16.711642             True